# Generated by Django 6.0.6 on 2026-06-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('twarz', 'Twarz'), ('rzesy', 'Rzęsy & Brwi'), ('dlonie', 'Dłonie & Stopy'), ('cialo', 'Ciało'), ('pielegnacja', 'Pielęgnacja'), ('solarium', 'Opalenizna')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
