# Generated by Django 6.0.6 on 2026-06-18 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0002_alter_employee_first_name_alter_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.employee'),
        ),
    ]
